- name: Update all packages to the latest version
  apt:
    update_cache: yes
    cache_valid_time: 864000  # 86400 1 day
    upgrade: dist
    autoclean: yes
    autoremove: yes
    purge: yes
  become: true

- name: apt update after fresh install HACK Check exists
  stat:
    path: /etc/apt/apt-update-after-fresh-install
  register: apt_update_after_fresh_install_result

- name: apt update after fresh install HACK apt update
  command: "apt-get update"
  args:
    warn: false
  when: apt_update_after_fresh_install_result.stat.exists == False 
  become: true

- name: apt update after fresh install HACK add file
  file:
    path: /etc/apt/apt-update-after-fresh-install
    state: directory
  become: true

- name: Reboot system if required
  command: shutdown -r now 'Rebooting to complete system upgrade'
  args:
    removes: /var/run/reboot-required
  become: true

- name: set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai
  become: true
