- name: restart apache2
  service: name=apache2 state=restarted
  become: true

- name: reload apache2
  service: name=apache2 state=reloaded
  become: true

- name: restart smokeping
  service: name=smokeping state=restarted
  become: true
